config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  match 'users/:id' => 'users#show', via: :get, as: 'profile'

  resources :pictures

  root 'categories#index'

  get '/faq' => 'info#faq'

  get '/members' => 'info#members'

  get '/contact' => 'info#contact'

  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base

	require 'carrierwave/orm/activerecord'
	
	belongs_to :user
	belongs_to :category

	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :pictures


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name,:last_name,:username,:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name,:last_name,:username,:email, :bio, :avatar, :password, :password_confirmation, :current_password, :location, :twitter, :facebook, :instagram, :tumblr, :interests) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def faq
  end

  def members
  	@users = User.all
  end

  def contact
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @pictures = Picture.all
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    @categories = Category.all 
    @users = User.all
  end

  # GET /pictures/1/edit
  def edit
    @categories = Category.all 
    @users = User.all
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :image, :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :title, :notes, :category_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
    <% @categories.each do |category| %>
        <div class="header">
            <h1><%= link_to category.name, category %></h1>
        </div>

        <div class="row">
            <!-- Shows 6 most recent thumbnails in each category -->
            <% category.pictures.sort_by{|t| - t.created_at.to_i}.first(6).each do |picture|%>
                <div class="col-xs-6 col-s-4 col-lg-2 thumbnails">
                    <%= link_to image_tag(picture.image_url, class: "img-responsive"), picture_path(picture.id) %>
                </div>
                    <% end %>
        </div>
            <% end %>
</div>
    

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container-fluid">
	<h1 class="header">Browse <%= @category.name %></h1>
	
	<div class="row">
    	<div class="col-xs-6 col-s-4 col-lg-2">
      		<!-- thumbnails will go here -->
    	</div>
  	</div>
</div>

<%= link_to 'Back', categories_path %>

app/views/info/contact.html.erb
<div class="container-fluid">
	<h1 class="header">Staff & Contact</h1>
	<div class="row">
		<div class="col-xs-12 col-sm-6 staff">
			<%= image_tag('romina.png', class: 'img-responsive') %>
			<h1>Romina aka username</h1>
			<p>Bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio </p>
		
			<ul class="list-inline contact-links">
				<li><%= link_to image_tag('twitter.png'), "http://www.twitter.com/blaedgith", :target => "_blank" %></li>
				<li><%= link_to image_tag('tumblr.png'), "http://githshaw.tumblr.com", :target => "_blank" %></li>
				<li><%= link_to image_tag('instagram.png'), "http://www.instagram.com/githshaw", :target => "_blank" %></li>
			</ul>
		</div>

		<div class="col-xs-12 col-sm-6 staff">
			<%= image_tag('mariel.png', class: 'img-responsive') %>
			<h1>Mariel aka melvinopolis</h1>
			<p>Bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio </p>
		
			<ul class="list-inline contact-links">
				<li><%= link_to image_tag('twitter.png'), "http://www.twitter.com/melvinopolis", :target => "_blank" %></li>
				<li><%= link_to image_tag('facebook.png'), "http://www.facebook.com/melvincosplay", :target => "_blank" %></li>
				<li><%= link_to image_tag('instagram.png'), "http://www.instagram.com/melvinopolis", :target => "_blank" %></li>
			</ul>
		</div>
	</div><!-- end row -->
</div><!-- end container -->

app/views/info/faq.html.erb
<div class="container-fluid">
	<h1 class="header">FAQ</h1>
	
	<div class="faq">
		<div class="well">
			<p><strong>Q: What is gllry?</strong></p>
			<p>Gllry is a web application designed to display your artwork, like an online portfolio!</p>
		</div>

		<div class="well">
			<p><strong>Q: Do you have premium memberships?</strong></p>
			<p>A: Everybody is premium!</p>
		</div>

		<div class="well">
			<p><strong>Q: Are there any other features coming to gllry?</strong></p>
			<p>A: Yes! Keep an eye out soon for comments, favorites, and username mentions!</p>
		</div>

		<div class="well">
			<p><strong>Q: Do you have a life motto?</strong></p>
			<p>A: If you fail to plan, you plan to fail.</p>
		</div>

		<div class="well">
			<p><strong>Q: What do I do if I forget my password?</strong></p>
			<p>A: Right now, please don't! But soon we will implement an email system which will allow for password recovery.</p>
		</div>

		<% if user_signed_in? %>
			<div class="well">
				<p><strong>Q: Can I delete my account if I don't like it?</strong></p>
				<p>A: We hope you don't want to leave, but if you do...here is the link: <%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-default" %></p>
			</div>
		<% else %>
			<div class="well">
			<p><strong>Q: Can I delete my account if I don't like it?</strong></p>
				<p>A: We hope you don't want to leave, but if you do...here is the link: [must be logged in to see this link!]"</p>
			</div>
		<% end %>
	</div> <!-- end faq -->
</div> <!-- end container -->

app/views/info/members.html.erb
<div class="container-fluid">
	<h1 class="header">Members</h1>
	<div class="row">
		
			<ul class="list-inline center-block members" >	
				<% @users.each do |user| %>
					<% if user.avatar? == true %>
						<li class="col-xs-6 col-sm-3 col-m-2"><%= link_to image_tag(user.avatar_url, class: "img-responsive"), profile_path(user.id) %>
						<%= user.username %></li>
					<% else %>
						<li class="col-xs-6 col-sm-3 col-m-2"><%= link_to image_tag("gllry.png", class: "img-responsive"), profile_path(user.id) %>
						<%= user.username %></li>
					<% end %>
				<% end %>
				<!-- Need to figure how to make them not stacked... -->
			</ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gllry</title>
  <link href='http://fonts.googleapis.com/css?family=Give+You+Glory|PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to image_tag("gllry.png"), root_path, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "Browse", pictures_path %></li> 
	        <li><%= link_to "Members", members_path %></li>
	        <li><%= link_to "FAQ", faq_path %></li>
	        <% if user_signed_in? %>
	        	<li><%= link_to "Submit", new_picture_path, class: "btn" %></li>
	        <% end %>
	      	<li class="divider"></li>
	      </ul>

	      <ul class="nav navbar-nav navbar-right">
	        <% if user_signed_in? %>
	        	<li class="dropdown">
	          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
	          		<% if current_user.avatar? == true %>
						<%= image_tag(current_user.avatar, class: "nav-icon") %>
					<% else %>
						<%= image_tag("gllry.png", class: "nav-icon") %>
					<% end %>	
	          		<%= current_user.username %> <span class="caret"></span></a>
	          		<ul class="dropdown-menu" role="menu">
	          			<li><%= link_to "Your Profile", profile_path(current_user) %></li>
	          			<li class="divider"></li>
						<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
						<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
					</ul>
				</li>
			<% else %>
				<li><%= link_to "Register", new_user_registration_path %></li>
				<li><%= link_to "Log In", new_user_session_path %></li>
			<% end %>
	        
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<footer class="container-fluid">
	<p>&copy; gllry 2015</p>
	<ul>
		<li><%= link_to "FAQ", faq_path %></li>
		<li><%= link_to "Staff & Contact", contact_path %></li>
	</ul>
</footer>
</body>
</html>

app/views/pictures/_form.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-s-6">
          <%= bootstrap_form_for(@picture, html: {class: "well"}) do |f| %>
            <% if @picture.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

                <ul>
                <% @picture.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.file_field :image %>
            </div>
            <div class="field">
              <%= f.text_field :title %>
            </div>
            
            <div class="field">
              <%= f.text_area :notes %>
            </div>
            <div class="field">
              <%= f.collection_select :category_id, @categories, :id, :name %>
            </div>
            <div class="field">
              <%= f.collection_select :user_id, @users, :id, :username %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="container-fluid">
  	<h1 class="header">Browse All Art</h1>
  		<div class="row">
  			<!-- Thumbnails sorted with most recent at the top -->
    		<% @pictures.sort_by{|t| - t.created_at.to_i}.each do |picture| %>
				<div class="col-xs-4 col-s-3 thumbnails">
					<%= link_to image_tag(picture.image_url, class: "img-responsive"), picture_path(picture.id)%>
    			</div>
    		<% end %>
  		</div>
</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<div class="container-fluid image">
  <%= image_tag(@picture.image_url, class: "img-responsive") %>
</div>


<div class="container-fluid description">
	<h1><%= @picture.title %></h1>
  	
  	<h4>by <%= @picture.user.username %></h4>
	
	<p class="notes"><%= @picture.notes %></p>

	<strong>Category:</strong>
  	<%= @picture.category.name %>
</div>


<div class="links">
	<% if user_signed_in? %>
		<% if @picture.user_id == current_user.id %>
			<%= link_to 'Edit', edit_picture_path(@picture) %> | <%= link_to 'Delete', @picture, method: :delete, data: { confirm: 'Are you sure?' } %> |
			<%= link_to 'Back', pictures_path %>
		<% else %>
			<%= link_to 'Back', pictures_path %>
		<% end %>
	<% else %>
		<%= link_to 'Back', pictures_path %>
	<% end %>
</div>

app/views/users/show.html.erb
<!-- User profile page -->
<div class="container-fluid">
	<div class="profile"><h1><%= @user.username %></h1></div>
	<div class="row">
        <div class="col-xs-12 col-sm-6 avatar">
        	<% if @user.avatar? == true %>
                <%= image_tag(@user.avatar_url, class: "img-responsive") %>
            <% else %>
                <%= image_tag("gllry.png", class: "img-responsive") %>
            <% end %>
        </div>
        <div class="col-xs-12 col-sm-6 bio">
        	<p><strong>Name: </strong><%= @user.first_name %> <%= @user.last_name.first %></p>
            <p><strong>Location: </strong><%= @user.location %></p>
        	<p><strong>About: </strong><%= @user.bio %></p>
            <p><strong>Interests: </strong><%= @user.interests %></p>

            <p><strong>Contact:</strong></p>
            <ul class="list-inline contact-links">
                <li><%= link_to image_tag('twitter.png'), @user.twitter, :target => "_blank" if @user.twitter? %></li>
                <li><%= link_to image_tag('facebook.png'), @user.facebook, :target => "_blank" if @user.facebook? %></li>
                <li><%= link_to image_tag('instagram.png'), @user.instagram, :target => "_blank" if @user.instagram? %></li>
                <li><%= link_to image_tag('tumblr.png'), @user.tumblr, :target => "_blank" if @user.tumblr? %></li>
            </ul>
        </div>
    </div>

<!-- User gallery with thumbnails sorted by most recent -->
    <div class="header">
    	<h1><%= @user.username %>'s Gallery</h1>
    </div>
        
    <div class="row">
            <% @user.pictures.sort_by{|t| - t.created_at.to_i}.each do |picture| %>
        <div class="col-xs-4 col-s-3 thumbnails">
               <%= link_to image_tag(picture.image_url, class: "img-responsive"), picture_path(picture.id) %>
        </div>   
            <% end %>    
    </div>
</div> <!-- end container -->